"""Reference side of the `charsets` conformance suite: CPython's codec registry, live.

`runtime-ts/src/charsets.ts` is GENERATED by `runtime-ts/scripts/charsets-table.py` from the
interpreter that ran it, and the port decodes single-byte MIME charsets through it. Two things
can drift: the checked-in file can fall behind the generator (someone edits the script and
forgets to regenerate), and the generator's output can fall behind the interpreter (a CPython
upgrade adds a codec or an alias). This script answers both from the registry itself, not
from the generator's output — every table below is `bytes([b]).decode(codec, errors="replace")`
over all 256 bytes, computed here — and ALSO runs the generator, so the suite can compare the
checked-in file to what it would write today.

Protocol: one JSON request on stdin, one JSON response on stdout.

    {"codecs": [<module name>, ...], "multi": [<module name>, ...]}
      -> {"version": "3.12.13",
          "generated": <the generator's stdout, verbatim>,
          "modules": [...], "aliases": {...},
          "tables": {<codec>: <256-character string>, ...},
          "multi_singles": {<codec>: <128-character string>, ...}}

`tables` is keyed by the names the SUITE asks for (the port's table keys), so a codec the port
carries and CPython no longer has answers `null` rather than a harness crash.
"""

from __future__ import annotations

import codecs
import encodings
import encodings.aliases
import json
import pkgutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
GENERATOR = REPO / "runtime-ts" / "scripts" / "charsets-table.py"


def _table(codec: str) -> str | None:
    try:
        codecs.lookup(codec)
    except LookupError:
        return None
    return "".join(bytes([b]).decode(codec, errors="replace") for b in range(256))


def _multi_singles(codec: str) -> str | None:
    try:
        codecs.lookup(codec)
    except LookupError:
        return None
    chars = [bytes([b]).decode(codec, errors="replace") for b in range(128, 256)]
    return "".join(c if len(c) == 1 else "�" for c in chars)


def main() -> None:
    payload = json.loads(sys.stdin.buffer.read().decode("utf-8"))
    # THE GENERATOR'S OUTCOME IS REPORTED, NOT ASSUMED. `check=True` used to turn a failure
    # into a traceback whose only trace on the other side was `generated: null` and a
    # `TypeError: Cannot read properties of null (reading 'replace')` — a crash of the whole
    # conformance run, on Windows, with nothing in it naming the generator. Measured on CI
    # 2026-09-05; the suite has never once completed on that platform.
    #
    # Whatever went wrong now arrives as data the suite can turn into a failing CASE.
    done = subprocess.run(
        [sys.executable, str(GENERATOR)], capture_output=True, text=True, encoding="utf-8"
    )
    generated = done.stdout if done.returncode == 0 else None
    out = {
        "version": sys.version.split()[0],
        "generated": generated,
        "generator": {
            "path": str(GENERATOR),
            "exists": GENERATOR.exists(),
            "returncode": done.returncode,
            "stderr": (done.stderr or "")[-4000:],
            "stdout_bytes": len(done.stdout or ""),
        },
        "modules": sorted(m.name for m in pkgutil.iter_modules(encodings.__path__)),
        "aliases": dict(encodings.aliases.aliases),
        "tables": {c: _table(c) for c in payload.get("codecs", [])},
        "multi_singles": {c: _multi_singles(c) for c in payload.get("multi", [])},
    }
    json.dump(out, sys.stdout, ensure_ascii=True)


if __name__ == "__main__":
    main()
