/**
 * charsets — the port's copy of CPython's codec registry, against the registry itself.
 *
 * THE PROPERTY: `runtime-ts/src/charsets.ts` is not a second registry kept in step by hand;
 * it is CPython's, written out by `runtime-ts/scripts/charsets-table.py`, and this suite is
 * what makes that a measurement. Two comparisons, because two things drift independently:
 *
 *   1. THE FILE AGAINST THE GENERATOR. The checked-in `charsets.ts` is compared byte for byte
 *      with what the generator writes today, header line excluded — the header names the
 *      interpreter's version, which the note reports instead, so a `3.12.13` venv and a
 *      `3.12.x` CI runner compare the tables and not the banner. An edited script whose
 *      output was never regenerated fails here.
 *   2. THE TABLES AGAINST THE INTERPRETER. For every codec the port carries, all 256 bytes
 *      are decoded by the REFERENCE (`bytes([b]).decode(codec, errors="replace")`, computed
 *      in `ref/charsets_ref.py`, not read back from the generator) and compared to what the
 *      port's table says — the low half is ASCII unless the table carries a `low` (the
 *      EBCDIC pages). The alias map and the module list are compared whole. A CPython that
 *      changed a table, added an alias or dropped a module fails here even if the file and
 *      the generator still agree with each other.
 *
 * Nothing here is a ruling: the port is REQUIRED to answer for the registry it was generated
 * from, and a difference is a stale file, never a decision.
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const name = 'charsets';
export const summary = 'src/charsets.ts against the live CPython codec registry: the generator\'s output and every single-byte table';

const here = dirname(dirname(fileURLToPath(import.meta.url)));
const REF = join(here, 'ref', 'charsets_ref.py');

const ASCII = Array.from({ length: 128 }, (_, i) => String.fromCharCode(i)).join('');
const HEADER = /^\/\/ Registry: CPython .*\n/m;

export async function run(ctx) {
  const charsets = await import(pathToFileURL(join(ctx.runtimeTs, 'dist', 'charsets.js')).href);
  const source = readFileSync(join(ctx.runtimeTs, 'src', 'charsets.ts'), 'utf8');
  const codecs = Object.keys(charsets.SINGLE_BYTE_TABLES).sort();
  const multi = Object.keys(charsets.MULTI_BYTE_SINGLES).sort();
  const python = ctx.runPython(REF, { codecs, multi });

  const cases = [];
  const notes = [];

  const fileVersion = source.match(HEADER)?.[0].match(/CPython (\S+)/)?.[1] ?? null;
  cases.push({
    name: 'src/charsets.ts is what scripts/charsets-table.py writes for the live registry (header line excluded)',
    kind: 'bytes',
    expected: python.generated.replace(HEADER, ''),
    actual: source.replace(HEADER, ''),
  });
  cases.push({
    name: 'src/charsets.ts carries the generator\'s header',
    kind: 'json',
    expected: true,
    actual: HEADER.test(source) && source.startsWith('// GENERATED by scripts/charsets-table.py'),
  });
  cases.push({ name: 'CODEC_MODULES is what pkgutil finds under encodings', kind: 'json', expected: python.modules, actual: [...charsets.CODEC_MODULES].sort() });
  cases.push({ name: 'CODEC_ALIASES is encodings.aliases.aliases', kind: 'json', expected: python.aliases, actual: charsets.CODEC_ALIASES });
  for (const codec of codecs) {
    const table = charsets.SINGLE_BYTE_TABLES[codec];
    cases.push({
      name: `single-byte ${codec}: all 256 bytes decode as CPython decodes them (errors="replace")`,
      kind: 'bytes',
      expected: python.tables[codec] ?? `<no such codec on the reference: ${codec}>`,
      actual: `${table.low ?? ASCII}${table.high}`,
    });
  }
  for (const codec of multi) {
    cases.push({
      name: `multi-byte ${codec}: which of 0x80..0xFF is a character on its own to CPython`,
      kind: 'bytes',
      expected: python.multi_singles[codec] ?? `<no such codec on the reference: ${codec}>`,
      actual: charsets.MULTI_BYTE_SINGLES[codec],
    });
  }
  notes.push(
    `${codecs.length} single-byte codecs, ${multi.length} multi-byte codecs' single bytes, ${Object.keys(charsets.CODEC_ALIASES).length} aliases, ` +
      `${charsets.CODEC_MODULES.size} modules; src/charsets.ts was generated by CPython ${fileVersion}, the reference here is CPython ${python.version}`,
  );
  return { cases, notes };
}
