"""Write `src/charsets.ts`: the CPython codec registry, as far as `docread.ts` mirrors it.

    ../.venv/bin/python scripts/charsets-table.py > src/charsets.ts

Nothing in the output is typed by hand. For every module under `encodings` that is a
stateless single-byte codec — each byte decodes to exactly one character, and a pair
decodes to the concatenation — the 256 characters `bytes([b]).decode(module,
errors="replace")` answers are written out (the low half only when it is not ASCII);
the alias table is `encodings.aliases.aliases` verbatim; the module list is what
`pkgutil` finds, because `encodings.search_function` resolves a name to a module and
`LookupError` is the absence of one. The interpreter that wrote the file is named in the
header, so a reader can tell which registry the port answers for.
"""

import codecs
import encodings
import encodings.aliases
import json
import pkgutil
import sys

ASCII = [chr(i) for i in range(128)]
# The CJK codecs `docread.ts` decodes through `TextDecoder`; for each, which bytes 0x80..0xFF
# are a character ON THEIR OWN to CPython (the halfwidth kana of shift_jis, cp932's 0x80),
# because ICU's tables accept C1 bytes Python refuses.
MULTI_BYTE = ("shift_jis", "cp932", "euc_jp", "gb2312", "gbk", "gb18030", "big5", "big5hkscs", "euc_kr", "cp949")
# Not byte codecs: text-to-text transforms and the sentinel that refuses everything.
NOT_BYTE_CODECS = {"charmap", "raw_unicode_escape", "unicode_escape", "rot_13", "undefined"}


def single_byte(module: str) -> tuple[str, str | None] | None:
    """The 256 characters `module` maps its bytes to, or `None` if it is not that kind of codec.

    THE PAIR SWEEP IS EVERY LEAD BYTE — all 65,536 ordered pairs — and that is review round 4
    (H1). It used to probe six hand-picked leads (0x41, 0x80, 0xA4, 0xD0, 0xE9, 0xFF), and
    neither ESC (0x1B) nor `~` (0x7E) is among them, so every STATEFUL codec walked straight
    through: a codec whose decoder carries state set by earlier bytes answers each byte alone
    with exactly one character (an incomplete escape is one U+FFFD) and passes a probe that
    never hands it the start of an escape. MEASURED: seven modules were written out with a
    256-character table they cannot have — `hz` and the six `iso2022_jp*` — and the port then
    decoded them one byte at a time, so `iso2022_jp` bytes for こんにちは came back as
    "\ufffd$B$3$s$K$A$O\ufffd(B" where the reference answers こんにちは. The full sweep refuses
    all seven — at (27, 0) for the ISO-2022 family and (126, 10) for `hz` — and still admits
    every genuine single-byte codec.

    The property is the one the table CLAIMS, stated over the whole domain instead of over a
    sample: a stateless byte codec decodes any ordered pair as the concatenation of the two
    bytes decoded alone. A codec that fails that anywhere is not a byte-to-character map and
    gets no row here.
    """
    try:
        chars = [bytes([b]).decode(module, errors="replace") for b in range(256)]
        if any(len(c) != 1 for c in chars):
            return None
        for a in range(256):
            lead = chars[a]
            for b in range(256):
                if bytes([a, b]).decode(module, errors="replace") != lead + chars[b]:
                    return None
    except Exception:  # noqa: BLE001 — a codec that is not a byte codec fails any which way
        return None
    high = "".join(chars[128:])
    low = None if chars[:128] == ASCII else "".join(chars[:128])
    return high, low


def main() -> None:
    modules = sorted(m.name for m in pkgutil.iter_modules(encodings.__path__))
    tables = {}
    for module in modules:
        if module in NOT_BYTE_CODECS:
            continue
        try:
            codecs.lookup(module)
        except LookupError:
            continue
        got = single_byte(module)
        if got is None:
            continue
        high, low = got
        tables[module] = {"high": high, **({"low": low} if low is not None else {})}
    singles = {}
    for module in MULTI_BYTE:
        chars = [bytes([b]).decode(module, errors="replace") for b in range(128, 256)]
        singles[module] = "".join(c if len(c) == 1 else "\ufffd" for c in chars)
    out = sys.stdout
    out.write("// GENERATED by scripts/charsets-table.py — do not edit; regenerate with\n")
    out.write("//     ../.venv/bin/python scripts/charsets-table.py > src/charsets.ts\n")
    out.write(f"// Registry: CPython {sys.version.split()[0]} ({len(tables)} single-byte codecs, ")
    out.write(f"{len(encodings.aliases.aliases)} aliases, {len(modules)} modules).\n\n")
    out.write("/** Every module `encodings` ships, as `encodings.search_function` would import it. */\n")
    out.write("export const CODEC_MODULES: ReadonlySet<string> = new Set(")
    out.write(json.dumps(modules, ensure_ascii=True) + ");\n\n")
    out.write("/** `encodings.aliases.aliases`: normalized name -> module. */\n")
    out.write("export const CODEC_ALIASES: Readonly<Record<string, string>> = ")
    out.write(json.dumps(encodings.aliases.aliases, ensure_ascii=True, sort_keys=True, indent=2) + ";\n\n")
    out.write("/**\n * Module -> the 128 characters bytes 0x80..0xFF decode to (`errors=\"replace\"`), and the\n")
    out.write(" * 128 for 0x00..0x7F only where they are not ASCII (the EBCDIC pages).\n */\n")
    out.write("export const SINGLE_BYTE_TABLES: Readonly<Record<string, { high: string; low?: string }>> = ")
    out.write(json.dumps(tables, ensure_ascii=True, sort_keys=True, indent=2) + ";\n\n")
    out.write("/**\n * The CJK modules, each -> what bytes 0x80..0xFF decode to ALONE (U+FFFD: not a\n")
    out.write(" * character by itself, so a lead byte or a refusal).\n */\n")
    out.write("export const MULTI_BYTE_SINGLES: Readonly<Record<string, string>> = ")
    out.write(json.dumps(singles, ensure_ascii=True, sort_keys=True, indent=2) + ";\n")


if __name__ == "__main__":
    main()
