#!/usr/bin/env python3
"""Render `assets/evals/devteam/tasks/*.yaml` from `manifest.yaml` + `repo/`.

The harness only understands an inline `workspace:` mapping (`evalrun.py:93-122`,
attached at `evalrun.py:435`), and no two tasks can share one — M1 gap 1. So the
repo surface is authored ONCE as real files under `repo/` and inlined into every
task by this script. The generated YAMLs are the runnable asset; `manifest.yaml`
plus `repo/` is the source of truth.

    build_tasks.py build    # (re)write tasks/*.yaml
    build_tasks.py check    # exit 1 if any task on disk differs from the manifest

`check` exists because a hand-edited task file would silently decouple the
runnable workload from its committed rationale and reference walks.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ASSET = Path(__file__).resolve().parents[2] / "assets" / "evals" / "devteam"
# Every task declares both workspace tools, so FileAccessGraph attaches on all of
# them (`evalrun.py:535` gates on a workspace tool being present).
TOOLS = ["read_file", "list_files"]


def load_manifest(asset: Path = ASSET) -> dict:
    return yaml.safe_load((asset / "manifest.yaml").read_text(encoding="utf-8"))


def load_repo(asset: Path = ASSET, root: str = "repo") -> dict[str, str]:
    """Every file under `repo/`, keyed by its repo-relative posix path."""
    base = asset / root
    # SORT THE POSIX KEY, NOT THE Path. `sorted(base.rglob("*"))` orders `Path` objects,
    # and the two flavours disagree: `PurePosixPath` compares case-SENSITIVELY, so
    # `HISTORY.md` and `README.md` precede `docs/...`, while `PureWindowsPath` folds case
    # and puts `docs/...` first. Six of these seventeen files land in a different position,
    # the workspace dict is built in a different insertion order, the rendered YAML differs,
    # and `check` reports all eight tasks as drifted -- on Windows only, against files that
    # nobody touched. Measured, not inferred: sorting the two flavours over this exact file
    # list disagrees on 6 of 17 entries. The key is already declared posix one line up;
    # ordering by it is what makes this generator produce the same bytes on every platform.
    pairs = sorted(
        (str(p.relative_to(base).as_posix()), p) for p in base.rglob("*") if p.is_file()
    )
    return {key: p.read_text(encoding="utf-8") for key, p in pairs}


def render(task: dict, workspace: dict[str, str]) -> str:
    # Key order is authored, not sorted: it matches the frozen tasks' shape so a
    # reader can diff a devteam task against a `nav-` task line for line.
    body = {
        "name": task["name"],
        "family": task["family"],
        "tools": TOOLS,
        "workspace": workspace,
        "prompt": task["prompt"].strip(),
        "scoring": task["scoring"],
    }
    header = (
        "# GENERATED by tools/devteam/build_tasks.py from"
        " assets/evals/devteam/manifest.yaml.\n"
        "# Do not hand-edit: `build_tasks.py check` fails if you do. The task's"
        " selection\n"
        "# rationale, reference walk and exclusion record live in the manifest.\n"
    )
    return header + yaml.safe_dump(body, sort_keys=False, allow_unicode=True, width=100)


def build(asset: Path = ASSET, write: bool = True) -> dict[str, str]:
    manifest = load_manifest(asset)
    workspace = load_repo(asset, manifest["surface"]["root"])
    missing = [
        (t["name"], hop["path"])
        for t in manifest["tasks"]
        for hop in t["walk"]
        if hop["path"] not in workspace
    ]
    if missing:
        raise SystemExit(f"reference walk names paths that are not in the repo: {missing}")
    out = {t["name"]: render(t, workspace) for t in manifest["tasks"]}
    if write:
        target = asset / "tasks"
        target.mkdir(parents=True, exist_ok=True)
        for name, text in out.items():
            (target / f"{name}.yaml").write_text(text, encoding="utf-8")
    return out


def check(asset: Path = ASSET) -> int:
    expected = build(asset, write=False)
    target = asset / "tasks"
    on_disk = {p.stem: p.read_text(encoding="utf-8") for p in sorted(target.glob("*.yaml"))}
    drifted = sorted(set(expected) ^ set(on_disk)) + sorted(
        name for name in expected if name in on_disk and on_disk[name] != expected[name]
    )
    if drifted:
        print("DRIFT — these tasks do not match the manifest: " + ", ".join(drifted))
        return 1
    print(f"OK — {len(expected)} task(s) match the manifest")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=["build", "check"])
    args = parser.parse_args(argv)
    if args.action == "check":
        return check()
    out = build()
    print(f"wrote {len(out)} task(s) to {ASSET / 'tasks'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
